name: Update LeetCode Contest Ratings Diagrams

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:  # <-- Add this to enable manual triggering

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository and submodules
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize and update submodules

    # (Optional) Update submodules to the latest version
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin main

    # Set up Python 3.12
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib numpy

    # Run the script to generate diagrams
    - name: Generate diagrams
      run: |
        python main.py

    # Commit and push the changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated update of contest ratings diagrams"
        git push