name: Update LeetCode Contest Ratings Diagrams
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Enables manual triggering

jobs:
  update-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib numpy

      - name: Generate diagrams
        run: |
          python main.py

      - name: Debug - List files and show git status
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Git status:"
          git status

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          echo "Git status before commit:"
          git status
          
          echo "Git diff:"
          git diff
          
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected, committing..."
            git add .
            git commit -m "Automated update of contest ratings diagrams"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Debug - Final git status
        run: |
          echo "Final git status:"
          git status